name: Group Validation CI

on:
  push:
    branches:
      - group1
      - group2
      - group3
      - group4
      - group5
      - main

jobs:

  qc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment (cached)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: 01_GitHub/environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Run QC step
        shell: micromamba-shell {0}
        run: bash 01_GitHub/scripts/01-qc.sh 01_GitHub/data test_output 8

  seqkit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment (cached)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: 01_GitHub/environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Run count step
        shell: micromamba-shell {0}
        run: bash 01_GitHub/scripts/02-summarize-seqs.sh 01_GitHub/data test_output/seq_counts.tsv 8

  annotation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment (cached)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: 01_GitHub/environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Run annotation step
        shell: micromamba-shell {0}
        run: |
          bash 01_GitHub/scripts/00-download-db.sh
          bash 01_GitHub/scripts/03-annotation.sh 01_GitHub/data test_output 01_GitHub/data/db_trimmed.dmnd 8
  
  build-matrix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment (cached)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: 01_GitHub/environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Run build matrix
        shell: micromamba-shell {0}
        run: bash 01_GitHub/scripts/04-build-matrix.sh 01_GitHub/ci_input

  multiqc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment (cached)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: 01_GitHub/environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Run MultiQC
        shell: micromamba-shell {0}
        run: bash 01_GitHub/scripts/05-build-report.sh 01_GitHub/ci_input 01_GitHub/data/multiqc_config.yaml
